FROM cardcorp/r-java

RUN apt-get update && \
    apt-get -y install python3-pip curl libcurl4-openssl-dev libssl-dev libssh2-1-dev libjpeg-dev && \
    pip3 install --no-cache-dir notebook==5.2 && \
    apt-get purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set up R Kernel for Jupyter
RUN R --quiet -e "install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest', 'rJava', 'jpeg'))"
RUN R --quiet -e "devtools::install_github('IRkernel/IRkernel')"
RUN R --quiet -e "IRkernel::installspec()"

RUN curl -J -O https://lindnerdominik.2y.net/owncloud/index.php/s/adnVfdKycy3BcOE/download \
 && R -e "install.packages('romero.gateway_0.3.0.tar.gz', repos = NULL, type='source')"

ENV NB_USER romero
ENV HOME /home/${NB_USER}

RUN groupadd ${NB_USER} && useradd -g ${NB_USER} ${NB_USER}

# Copy repo into ${HOME}, make user own $HOME
USER root
COPY . ${HOME}
RUN chown -R ${NB_USER} ${HOME}
USER ${NB_USER}
WORKDIR ${HOME}

## run any install.R script we find
RUN if [ -f install.R ]; then R --quiet -f install.R; fi

